Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Admin-Area/Tags/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EFDataAccessLibrary.DataAccess;
using EFDataAccessLibrary.Models;

namespace Semester_Project.Pages.Admin_Area.Tags
{
    public class DetailsModel : PageModel
    {
        private readonly EFDataAccessLibrary.DataAccess.CoursesContext _context;

        public DetailsModel(EFDataAccessLibrary.DataAccess.CoursesContext context)
        {
            _context = context;
        }

        public Tag Tag { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Tag = await _context.Tags.Include(x => x.Courses).FirstOrDefaultAsync(m => m.Id == id);

            if (Tag == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EFDataAccessLibrary.DataAccess;
using EFDataAccessLibrary.Models;

namespace Semester_Project.Pages.Admin_Area.Courses
{
    public class DetailsModel : PageModel
    {
        private readonly EFDataAccessLibrary.DataAccess.CoursesContext _context;

        public DetailsModel(EFDataAccessLibrary.DataAccess.CoursesContext context)
        {
            _context = context;
        }

        public Course Course { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Course = await _context.Courses.Include(x => x.Tags).FirstOrDefaultAsync(m => m.Id == id);

            if (Course == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Semester_Project.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EFDataAccessLibrary.DataAccess;
using EFDataAccessLibrary.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Semester_Project.Pages.Admin_Area.Courses
{
    public class IndexModel : PageModel
    {
        private readonly EFDataAccessLibrary.DataAccess.CoursesContext _context;

        public IndexModel(EFDataAccessLibrary.DataAccess.CoursesContext context)
        {
            _context = context;
        }

        [BindProperty]
        public int SelectedTag { get; set; }
        public IList<Course> Course { get;set; }
        public SelectList TagOptions { get; set; }

        public async Task OnGetAsync()
        {
            Course = await _context.Courses.ToListAsync();
            TagOptions = new SelectList (_context.Tags.ToList(), nameof(Tag.Id), nameof(Tag.Name));
            SelectedTag = 0;
        }

        public IActionResult OnPostFilters(int SelectedTag)
        {
            var tag = _context.Tags.Find(SelectedTag);

            Course = _context.Courses
                .Include(c => c.Tags)
                .Where(x => x.Tags.Any(y => y.Id == tag.Id))
                .ToList();

            TagOptions = new SelectList(_context.Tags.ToList(), nameof(Tag.Id), nameof(Tag.Name));
            SelectedTag = 0;

            return Page();
        }
    }
}

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Semester_Project.AdoNet;
using Semester_Project.Models;

namespace Semester_Project.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IConfiguration _configuration;
        [BindProperty]
        public SiteUser user { get; set; }
        public LoginModel(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ValidateUser(user, _configuration))
            {
                var claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, user.Username)
                };
                var claimsIdentity = new ClaimsIdentity(claims, "CookieAuthentication");
                await HttpContext.SignInAsync("CookieAuthentication", new ClaimsPrincipal(claimsIdentity));
                return RedirectToPage("/Index");
            }
            return Page();
        }
        private static bool ValidateUser(SiteUser User, IConfiguration configuration)
        {
            string hash = CRUD.GetPasswordHash(User.Username, configuration);
            if (hash == null)
                return false;
            bool verified = BCrypt.Net.BCrypt.Verify(User.Password, hash);
            if (verified)
                return true;
            else
                return false;
        }
    }
}

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Semester_Project.Pages
{
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {
            await HttpContext.SignOutAsync("CookieAuthentication");
            return this.RedirectToPage("/index");
        }
    }
}

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Semester_Project.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Details.cshtml
@page
@model Semester_Project.Pages.Admin_Area.Courses.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1 class="display-4 text-center">Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Tags)
        </dt>
        <dd class="col-sm-10">
            @{  
                foreach (var item in Model.Course.Tags)
                {
                    <div>@item.Name</div>
                }
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-page="Admin-Area/Courses/Edit" asp-route-id="@Model.Course.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Index.cshtml
@page
@model Semester_Project.Pages.Admin_Area.Courses.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1 class="display-4 text-center">List of available courses</h1>

@if (User.Identity.IsAuthenticated && User.Identity.Name == "admin")
{
    <p>
        <a asp-page="Admin-Area/Courses/Create">Create New</a>
    </p>
}
    <h2>Filters</h2>
    <form method="post" asp-page-handler="filters">
        <div class="row pb-4">
            <div class="col-5">
                <select class="form-control" asp-for="SelectedTag" asp-items="Model.TagOptions"></select>
            </div>
            <div class="col-1 text-left">
                <button class="btn btn-primary">Apply</button>
            </div>
        </div>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Course[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Course[0].Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Course)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        <a asp-page="./Details" asp-route-id="@item.Id">Details</a>
                        @if (User.Identity.IsAuthenticated && User.Identity.Name == "admin")
                        {
                            <small>|</small> <a asp-page="Admin-Area/Courses/Edit" asp-route-id="@item.Id">Edit</a> 
                            <small>|</small> <a asp-page="Admin-Area/Courses/Delete" asp-route-id="@item.Id">Delete</a>
                        }
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Login.cshtml
@page
@model Semester_Project.Pages.LoginModel
@{
    ViewData["Title"] = "Index";
}
<h1 class="display-4 text-center">Login</h1>
<div class="container">
    <form class="form-horizontal" method="post">
        <div class="row justify-content-center">
            <div class="col-6 form-group">
                <label asp-for="user.Username" class="control-label"></label>
                 <input asp-for="user.Username" class="form-control">
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-6 form-group">
                <label asp-for="user.Password" class="control-label col-sm2"></label>
                 <input asp-for="user.Password" class="form-control">
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-6 form-group text-center">
                <button class="btn btn btn-primary">Zatwierdź</button>
            </div>
        </div>
    </form>
</div>

Semestr_IV/ASP_DOT_NET/Semester Project/Semester Project/Pages/Logout.cshtml
@page
@model Semester_Project.Pages.LogoutModel
@{
}